# Generated by Django 5.1.5 on 2025-07-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designation',
            options={},
        ),
        migrations.RemoveField(
            model_name='designation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='job_type',
        ),
    ]
