# Generated by Django 5.1 on 2025-02-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=25, unique=True)),
                ('designation', models.CharField(max_length=255)),
                ('present_address', models.CharField(max_length=255)),
                ('permanent_address', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joining_date', models.DateField()),
                ('employment_status', models.CharField(choices=[('full_time', 'Full Time'), ('permanent', 'Permanent'), ('intern', 'Intern'), ('part_time', 'Part Time'), ('contract_base', 'Contract Base')], default='Active', max_length=20)),
                ('employee_photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('employee_doc', models.FileField(blank=True, null=True, upload_to='employee_docs/')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filedescription', models.TextField()),
                ('file', models.FileField(upload_to='officialDocs/')),
            ],
        ),
    ]
