# Generated by Django 5.1.5 on 2025-02-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filedescription', models.TextField()),
                ('file', models.FileField(upload_to='officialDocs/')),
            ],
        ),
    ]
