# Generated by Django 5.1.5 on 2025-02-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeemployee',
            name='em_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
