# Generated by Django 5.1.5 on 2025-02-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_officeemployee_em_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officeemployee',
            old_name='em_id',
            new_name='employee_id',
        ),
    ]
