# Generated by Django 5.1.5 on 2025-03-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_officialdocument_documents_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
    ]
