# Generated by Django 5.1.5 on 2025-02-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_em_id_officeemployee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeemployee',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='officeemployee',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
