# Generated by Django 5.1.5 on 2025-04-23 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_travelrequest_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reimbursed', models.BooleanField(default=False)),
                ('reimbursed_on', models.DateField(blank=True, null=True)),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.expense')),
            ],
        ),
    ]
