# Generated by Django 5.1.5 on 2025-02-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_officeemployee_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeemployee',
            name='phone',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
